[project]
name = "pytaq"
version = "0.2.0"
description = "Module to process NYSE TAQ data"
readme = "README.md"
requires-python = ">=3.11,<3.13"
authors = [{ name = "Vincent Grégoire", email = "vincent.gregoire@hec.ca" }]
dependencies = [
    "ibis-framework>=9.5.0",
    "ibis-framework[duckdb,polars,postgres]>=9.5.0",
]


[tool.uv.pip]
only-binary = ["pyarrow"]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "polars>=1.13.0",
    "pyarrow>=17",
    "pytest>=8.3.3",
    "python-dotenv>=1.0.1",
]
